### ISSUE TITLE
can't install / latest version

### ISSUE THREAD

**Issue by christian-lo** [Keleo/DeductionTimeBundle#11]
Hi,
I tried to install this bundle within two kimai installations and it neither showed up in extensions nor does the checkbox appear within any activities. 
The folder DeductionTimeBundle and all files are visible within the var/plugins/ directory and the cache was reloaded. 
kimai v2.4.1 (prod)
Any ideas?

**Comment by kevinpapst** [comment]
Wrong directory name

**Comment by christian-lo** [comment]
OK, what's the right name? 
Actually I had one installation still running on kimai v2.3.1, installed DeductionTimeBundle and it didn't work. Then updated kimai to v2.4.1 and after the update the plugin appeared in extensions and was working fine. 
Sure there is no problem?

**Comment by christian-lo** [comment]
The dir name was copied from your install guide b.t.w.: DeductionTimeBundle
https://www.kimai.org/store/keleo-deduction-time-bundle.html

**Comment by kevinpapst** [comment]
> Sure there is no problem?

Yes. You might wanna restart PHP, in case the opcache is blocking a reload.
