### ISSUE TITLE
Reporting for all users shows only total amount of deducted time

### ISSUE THREAD

**Issue by Bibz87** [Keleo/DeductionTimeBundle#13]
Much like #8, the time displayed in the _Reporting_ -> _Weekly view for all users_ page doesn't show negative time.

After reading [this](https://github.com/Keleo/DeductionTimeBundle/issues/8#issuecomment-1931486765) comment I've looked at Kimai's code and it seems that `user_list_period_data.html.twig` still has a `> 0` check but I'm not sure if this is the right file for that specific reporting page.

I'm currently running Kimai's and the plugin's latest versions: 2.13.0 and 2.0.1, respectively.

Any help would be appreciated.

Thanks!

**Comment by kevinpapst** [comment]
I am not using that feature... but you could try to adjust the template and in case it fixes the issues: send a PR!?

😄

**Comment by Bibz87** [comment]
Sure!
