### ISSUE TITLE
drag&drop in calendar not possible

### ISSUE THREAD

**Issue by timopitt** [Keleo/DeductionTimeBundle#2]
Drag&Drop is not possible in the calendar view because the duration has stored a negative value. 
An attempt leads to an error message: Validation Failed This value should be greater than or equal to 0.

![image](https://user-images.githubusercontent.com/61874821/199233843-3f352429-5f94-40e7-9720-439fdf066428.png)

**Comment by kevinpapst** [comment]
I cannot confirm that. Do you have the latest Kimai installed? There were changes in Kimai core necessary, to allow negative durations. Your validation looks like you ignored the README:

<img width="479" alt="Bildschirmfoto 2022-11-01 um 15 12 37" src="https://user-images.githubusercontent.com/533162/199253911-2ca47acf-e569-4216-ad45-1ce74fc70989.png">

😁 

You can always test at the "Plugin Demo", see URL and accounts at https://www.kimai.org/demo/

**Comment by timopitt** [comment]
You are right, I ignored the README. Maybe you should correct the required version in composer.json too.

![image](https://user-images.githubusercontent.com/61874821/199428240-6046f3ea-7a45-40b1-90d6-286599fb637b.png)

**Comment by kevinpapst** [comment]
Good catch 👍 thanks for spotting!

Technically this is compatible with Kimai 1.20, but Kimai core has some issues with negative durations up until 1.27.0.
So I guess it is better to raise this requirement to 1.27.
