### ISSUE TITLE
Installation Error Version: 1.30.1 stable (prod)

### ISSUE THREAD

**Issue by asaglam76** [Keleo/DeductionTimeBundle#3]
Hi,
I've installed this plugin on 1.29.1 stable (prod) for testing ... because of some issues I made a new installation the actual release 1.30.1 stable (prod).
The difference between two environment is, that 1.29 is running with php8.1 on ubuntu 20.04 and 1.30.1 with php8.2 on ubuntu 22.04.
The installation fails with following error ..

<<
PHP Fatal error:  Declaration of KimaiPlugin\DeductionTimeBundle\Timesheet\Calculator\DeductionTimeCalculator::calculate(App\Entity\Timesheet $record, array $changeset): void must be compatible with App\Timesheet\CalculatorInterface::calculate(App\Entity\Timesheet $record) in /var/www/html/kimai/var/plugins/DeductionTimeBundle/Timesheet/Calculator/DeductionTimeCalculator.php on line 19'
>>

**Comment by kevinpapst** [comment]
Install the compatible version, see https://github.com/Keleo/DeductionTimeBundle/tree/1.x#installation

**Comment by LadySolveig** [comment]
I ran into the same problem. For users that also misunderstood the installation instruction - you can not use the git clone for kimai version < 2.0
on Linux use 
<code>wget https://github.com/Keleo/DeductionTimeBundle/archive/refs/tags/1.0.tar.gz
tar -xf 1.0.tar.gz
mv DeductionTimeBundle-1.0 DeductionTimeBundle</code>

**Comment by kevinpapst** [comment]
Thanks @LadySolveig 👍 
This mixup will exist until 2.0 was released and all users updated. 
As that might take quite a while, I changed the wording of the installation docs. 
Hopefully is clearer now.
