### ISSUE TITLE
Automatically deduct time based on how long you worked

### ISSUE THREAD

**Issue by Does-This-Work** [Keleo/DeductionTimeBundle#6]
First of all I wanted to drop a massive thanks to the Kimai project. It works great for me! 

It would be helpful for me and my colleagues, if the time would be deducted automatically.

**For example:**
I have a 6 hour workday, I would like it to automatically deduct a 30 minute break from that day. I would then have worked for 5 hours and 30 minutes that day.

If I have a 8 hour workday, it should deduct a 45 minute break from that day. Basically I would work 7 hours and 15 minutes plus a 45 minute break.

Colleagues would be encouraged to take their breaks, since it would be deducted at the end of the day from their actual working hours.

**Comment by kevinpapst** [comment]
Won't be added. This plugin has one specific use-case.
