### ISSUE TITLE
Problem after Installation of the DeducationTimeBundle

### ISSUE THREAD

**Issue by Arthenis** [Keleo/DeductionTimeBundle#7]
Hello,

after I installed the DeducationTimeBundle, there was a error after reloading the cache. 
![Kimai Fehler](https://user-images.githubusercontent.com/121581610/229774939-14ab0400-ff2c-4c77-9d21-21f63ea8d206.png)
Could somebody please help me with that ? 
Thanks...

**Comment by kevinpapst** [comment]
See #4 and #5
